### PR TITLE
Tailwind CSS Framework Configuration

### PR DESCRIPTION
**Pull request by shodown96**
## Issue #111 : CSS Configuration( install tailwind css ) 
The React application was configured to work with Tailwind CSS framework to help in the implementation of designs. 
The `node_modules/` directory was also deleted as it wasn't supposed to be pushed to the repo initially. The directory has been added to the `.gitignore` file.
Test link: https://sales.zuri.chat
Slack username: Mikaelson

### CODE REVIEW

**Comment by Khadeeejah** [comment]
Please check the conflicting files @shodown96

**Comment by Khadeeejah** [comment]
pull request merged into the dev branch

**Comment by markessien** [comment]
Unclear what was done here

**Comment by shodown96** [comment]
The Tailwind CSS framework was configured to be used in the react application, The text currently seen is now able to use Tailwind classes.
preview

**Pull request merged**
